# version: "3.8"

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend_dev
    ports:
      - "5432:5432"

  backend:
    build: ./Backend
    env_file:
      - ./Backend/.env
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/backend_dev"
    #volumes:
    #  - ./Backend:/app

  frontend:
    build: ./Frontend
    ports:
      - "5173:80"
