version: "3.8"

services:
  backend:
    build: ./Backend
    env_file:
      - ./Backend/.env
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/my_app_prod"
    depends_on:
      - db

  frontend:
    build: ./Frontend
    ports:
      - "5173:80"

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_app_prod
    ports:
      - "5432:5432"
